import { enemyBaseStats } from "@/types/enemy.types";

export const STATS_GNOME: enemyBaseStats = {
  img: "/assets/enemy/gnome.png",
  name: "Гном-охранник",
  power: 85,
  agility: 80,
  intellect: 60,
  attack: 165,
  def: 32,
  magicDef: 10,
  maxHp: 2000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_2: enemyBaseStats = {
  img: "/assets/enemy/gnome_2.png",
  name: "Гном-воитель",
  power: 70,
  agility: 100,
  intellect: 50,
  attack: 125,
  def: 43,
  magicDef: 10,
  maxHp: 2100,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_3: enemyBaseStats = {
  img: "/assets/enemy/gnome_3.png",
  name: "Боевой гном",
  power: 125,
  agility: 55,
  intellect: 50,
  attack: 175,
  def: 51,
  magicDef: 10,
  maxHp: 2200,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_4: enemyBaseStats = {
  img: "/assets/enemy/gnome_4.png",
  name: "Гном-убийца",
  power: 100,
  agility: 60,
  intellect: 60,
  attack: 210,
  def: 36,
  magicDef: 15,
  maxHp: 2300,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_5: enemyBaseStats = {
  img: "/assets/enemy/gnome_5.png",
  name: "Владыка гномов",
  power: 110,
  agility: 50,
  intellect: 150,
  attack: 90,
  def: 30,
  magicDef: 25,
  maxHp: 3500,
  attackSpeed: 0.5,
  powerSkill: 0,
};
