import { enemyBaseStats } from "@/types/enemy.types";

export const STATS_GOBLIN: enemyBaseStats = {
  img: "/assets/enemy/goblin.png",
  name: "Гоблин-разведчик",
  power: 35,
  agility: 90,
  intellect: 40,
  attack: 110,
  def: 17,
  magicDef: 5,
  maxHp: 1600,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GOBLIN_2: enemyBaseStats = {
  img: "/assets/enemy/goblin_2.png",
  name: "Гоблин-убийца",
  power: 55,
  agility: 70,
  intellect: 50,
  attack: 140,
  def: 23,
  magicDef: 5,
  maxHp: 1700,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GOBLIN_3: enemyBaseStats = {
  img: "/assets/enemy/goblin_3.png",
  name: "Гоблин-ветеран",
  power: 100,
  agility: 45,
  intellect: 40,
  attack: 170,
  def: 36,
  magicDef: 10,
  maxHp: 1800,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GOBLIN_4: enemyBaseStats = {
  img: "/assets/enemy/goblin_4.png",
  name: "Гоблин-головорез",
  power: 115,
  agility: 70,
  intellect: 40,
  attack: 165,
  def: 32,
  magicDef: 15,
  maxHp: 1900,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GOBLIN_5: enemyBaseStats = {
  img: "/assets/enemy/goblin_5.png",
  name: "Охотник за головами",
  power: 90,
  agility: 90,
  intellect: 60,
  attack: 150,
  def: 32,
  magicDef: 20,
  maxHp: 3000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
