import { enemyBaseStats } from "@/types/enemy.types";

export const STATS_GNOME: enemyBaseStats = {
  img: "/assets/enemy/gnome.png",
  name: "Гном-охранник",
  power: 85,
  agility: 85,
  intellect: 60,
  attack: 175,
  def: 35,
  magicDef: 10,
  maxHp: 2000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_2: enemyBaseStats = {
  img: "/assets/enemy/gnome_2.png",
  name: "Гном-воитель",
  power: 70,
  agility: 105,
  intellect: 50,
  attack: 135,
  def: 45,
  magicDef: 10,
  maxHp: 2100,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_3: enemyBaseStats = {
  img: "/assets/enemy/gnome_3.png",
  name: "Боевой гном",
  power: 125,
  agility: 55,
  intellect: 50,
  attack: 190,
  def: 55,
  magicDef: 10,
  maxHp: 2200,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_4: enemyBaseStats = {
  img: "/assets/enemy/gnome_4.png",
  name: "Гном-убийца",
  power: 100,
  agility: 65,
  intellect: 60,
  attack: 220,
  def: 40,
  magicDef: 15,
  maxHp: 2300,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_5: enemyBaseStats = {
  img: "/assets/enemy/gnome_5.png",
  name: "Пещерный ужас",
  power: 125,
  agility: 40,
  intellect: 160,
  attack: 240,
  def: 34,
  magicDef: 25,
  maxHp: 3500,
  attackSpeed: 0.5,
  powerSkill: 0,
};
