import { enemyBaseStats } from "@/types/enemy.types";
export const STATS_GODLEN_PIG: enemyBaseStats = {
  img: "/assets/enemy/golden-pig.png",
  name: "Золотая свинка",
  power: 10,
  agility: 10,
  intellect: 10,
  attack: 50,
  def: 30,
  magicDef: 0,
  maxHp: 1000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_SWAMP_MONSTER: enemyBaseStats = {
  img: "/assets/enemy/swampMonster.png",
  name: "Болотное чудовище",
  power: 90,
  agility: 25,
  intellect: 10,
  attack: 170,
  def: 45,
  magicDef: 10,
  maxHp: 2500,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_TRADER: enemyBaseStats = {
  img: "/assets/enemy/gnome-trader.png",
  name: "Гном-торговец",
  power: 20,
  agility: 20,
  intellect: 20,
  attack: 100,
  def: 20,
  magicDef: 0,
  maxHp: 1500,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_CAVE_HORROR: enemyBaseStats = {
  img: "/assets/enemy/caveHorror.png",
  name: "Пещерный ужас",
  power: 120,
  agility: 10,
  intellect: 40,
  attack: 210,
  def: 40,
  magicDef: 20,
  maxHp: 3400,
  attackSpeed: 0.5,
  powerSkill: 0,
};

export const STATS_TREASURE_BOX: enemyBaseStats = {
  img: "/assets/enemy/treasureBox.png",
  name: "Cундук с сокровищем",
  power: 10,
  agility: 10,
  intellect: 10,
  attack: 150,
  def: 40,
  magicDef: 0,
  maxHp: 2000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_SEA_MONSTER: enemyBaseStats = {
  img: "/assets/enemy/seaMonster.png",
  name: "Морское чудовище",
  power: 160,
  agility: 15,
  intellect: 50,
  attack: 300,
  def: 50,
  magicDef: 30,
  maxHp: 4300,
  attackSpeed: 0.5,
  powerSkill: 0,
};
