import { enemyBaseStats } from "@/types/enemy.types";
export const STATS_GODLEN_PIG: enemyBaseStats = {
  img: "/src/assets/enemy/golden-pig.png",
  name: "Золотая свинка",
  power: 10,
  agility: 10,
  intellect: 10,
  attack: 50,
  def: 30,
  magicDef: 0,
  maxHp: 1000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_GNOME_TRADER: enemyBaseStats = {
  img: "/src/assets/enemy/gnome-trader.png",
  name: "Гном-торговец",
  power: 20,
  agility: 20,
  intellect: 20,
  attack: 100,
  def: 20,
  magicDef: 0,
  maxHp: 1500,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_SEA_MONSTER: enemyBaseStats = {
  img: "/src/assets/enemy/gnome-trader.png",
  name: "Морское чудовище",
  power: 200,
  agility: 20,
  intellect: 50,
  attack: 300,
  def: 50,
  magicDef: 0,
  maxHp: 4800,
  attackSpeed: 0.5,
  powerSkill: 0,
};
export const STATS_TREASURE_BOX: enemyBaseStats = {
  img: "/src/assets/enemy/treasureBox.png",
  name: "Cундук с сокровищем",
  power: 10,
  agility: 10,
  intellect: 10,
  attack: 150,
  def: 40,
  magicDef: 0,
  maxHp: 2000,
  attackSpeed: 0.5,
  powerSkill: 0,
};
